#define WIFI_SSID "yourSSID"
#define WIFI_PASSWORD "yourpass"

#define MQTT_HOST IPAddress(192, 168, 1, 10)
#define MQTT_PORT 1883

#define SEALEVELPRESSURE_HPA (1013.25)

#define SOIL_MOISTURE_TIMER_MS 3 * 60 * 1000 // in MS

// pins
#define WATERPUMP_PIN GPIO_NUM_13
#define SOIL_MOISTURE_SENSOR_PIN GPIO_NUM_36
